version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity 
    networks:
    - main
    environment:
      VOICEVOX_ENDPOINT: "http://voicevox:50021"
      DATABASE_URL: "postgresql://dev:dev@db:5432/dev"

  voicevox:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
    - "50021:50021"
    networks:
    - main

  db:
    image: postgres
    environment:
    - POSTGRES_USER=dev
    - POSTGRES_DB=dev
    networks:
    - main

networks:
  main: